parameters = {
    
    'timespan': {
    'min': 0,
    'max': 515
    },
    
    'temporal_resolution': 1,
    'buffer_distance': 6,
    'num_random': 10,
    'grid_resolution': 0.5,
    
    'plate_model_dir': 'plate_model',
    'inputs_dir': 'inputs',
    'outputs_dir': 'outputs',
    'buffer_zones_dir': 'buffer_zones',
    'ml_dir': 'ml',
    'backarc_prob_grids_dir': 'backarc_prob_grids',
    'backarc_entropy_grids_dir': 'backarc_entropy_grids',
    'backarc_vote_variance_grids_dir': 'backarc_vote_variance_grids',
    'backarc_prob_maps_dir': 'backarc_prob_maps',
    'backarc_entropy_maps_dir': 'backarc_entropy_maps',
    'backarc_vote_variance_maps_dir': 'backarc_vote_variance_maps',
    'coastline_prob_grids_dir': 'coastline_prob_grids',
    'coastline_entropy_grids_dir': 'coastline_entropy_grids',
    'coastline_vote_variance_grids_dir': 'coastline_vote_variance_grids',
    'coastline_prob_maps_dir': 'coastline_prob_maps',
    'coastline_entropy_maps_dir': 'coastline_entropy_maps',
    'coastline_vote_variance_maps_dir': 'coastline_vote_variance_maps',
    'pres_dir': 'preservation',
    'backarc_pres_grids_dir': 'backarc_pres_grids',
    'backarc_pres_maps_dir': 'backarc_pres_maps',
    'backarc_prob_pres_grids_dir': 'backarc_prob_pres_grids',
    'backarc_prob_pres_maps_dir': 'backarc_prob_pres_maps',
    'coastline_pres_grids_dir': 'coastline_pres_grids',
    'coastline_pres_maps_dir': 'coastline_pres_maps',
    'coastline_prob_pres_grids_dir': 'coastline_prob_pres_grids',
    'coastline_prob_pres_maps_dir': 'coastline_prob_pres_maps',
    
    'subduction_data_filename': 'subduction_data.csv',
    'deposit_coords_filename': 'deposit_coords_weight.csv',
    'deposit_coords_recon_filename': 'deposit_coords_recon.csv',
    'deposit_coords_recon_all_filename': 'deposit_coords_recon_all.csv',
    'unlabelled_coords_filename': 'unlabelled_coords.csv',
    'backarc_coords_filename': 'backarc_coords.csv',
    'deposit_data_filename': 'deposit_data.csv',
    'unlabelled_data_filename': 'unlabelled_data.csv',
    'backarc_data_filename': 'backarc_data.csv',
    'features_imputed_weight_label_filename': 'features_imputed_weight_label.csv',
    'corr_filename': 'corr.csv',
    'Xy_train_original_filename': 'Xy_train_original.csv',
    'Xy_pos_test_original_filename': 'Xy_pos_test_original.csv',
    'Xy_train_filename': 'Xy_train.csv',
    'Xy_pos_test_filename': 'Xy_pos_test.csv',
    'Xy_train_new_filename': 'Xy_train_new.csv',
    'Xy_rf_train_filename': 'Xy_rf_train.csv',
    'Xy_rf_val_filename': 'Xy_rf_val.csv',
    'Xy_rf_test_filename': 'Xy_rf_test.csv',
    'gini_importances_filename': 'gini_importances.csv',
    'permutation_importances_filename': 'permutation_importances.csv',
    'shap_values_filename': 'shap_values.csv',
    'features_shap_test_filename': 'features_shap_test.csv',
    'backarc_prob_filename': 'backarc_prob.csv',
    'coastlines_filename': 'coastlines.shp',
    'coastline_coords_filename': 'coastline_coords.csv',
    'coastline_data_filename': 'coastline_data.csv',
    'coastline_prob_filename': 'coastline_prob.csv',
    'coastline_prob_present_day_filename': 'coastline_prob_present_day.csv',
    'coastline_prob_present_day_grid_filename': 'coastline_prob_present_day_grid.nc',
    'coastline_entropy_present_day_grid_filename': 'coastline_entropy_present_day_grid.nc',
    'coastline_vote_variance_present_day_grid_filename': 'coastline_vote_variance_present_day_grid.nc',
    'gengamma_dist_filename': 'gengamma_dist.joblib',
    'deposit_ero_filename': 'deposit_ero.csv',
    'unlabelled_ero_filename': 'unlabelled_ero.csv',
    'backarc_ero_filename': 'backarc_ero.csv',
    'coastline_ero_filename': 'coastline_ero.csv',
    'coastline_prob_pres_present_day_grid_filename': 'coastline_prob_pres_present_day_grid',
    
    'robust_scaler_filename': 'robust_scaler.pkl',
    'model_pub_filename': 'model_pub.pkl',
    'model_rf_filename': 'model_rf.pkl',
    'model_rf_calibrated_filename': 'model_rf_calibrated.pkl',
    
    'columns_to_drop_deposit': [
        'present_lon',
        'present_lat',
        'age (Ma)',
        'weight',
        'label',
        'plate_id',
        'lon',
        'lat',
        'overriding_plate_id',
        'subducting_plate_ID',
        'trench_plate_ID',
        'distance_from_trench_start (km)',
        'trench_normal_angle (degrees)',
        ],
    
    'columns_to_drop_unlabelled': [
        'present_lon',
        'present_lat',
        'age (Ma)',
        'weight',
        'label',
        'lon',
        'lat',
        'overriding_plate_id',
        'subducting_plate_ID',
        'trench_plate_ID',
        'distance_from_trench_start (km)',
        'trench_normal_angle (degrees)',
        ],
    
    'columns_to_drop_backarc': [
        'present_lon',
        'present_lat',
        'age (Ma)',
        'lon',
        'lat',
        'subducting_plate_ID',
        'trench_plate_ID',
        'distance_from_trench_start (km)',
        'trench_normal_angle (degrees)',
        ]
    
    }
